# Generated by Django 3.2.5 on 2021-07-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=10, verbose_name='Contrasena')),
                ('comentarios', models.CharField(blank=True, max_length=20, null=True, verbose_name='Comentarios')),
            ],
        ),
    ]
