# Generated by Django 3.2.5 on 2021-07-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_vehiculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Libro',
        ),
    ]
